/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pm3.hs23.it22a_win.team1.dashboard;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        // TODO: 10.10.2023 Logger initialisieren
        Application.launch(DashboardUI.class, args);
    }
}
