/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pm3.hs23.it22a_win.team1;

import org.junit.jupiter.api.Test;
import pm3.hs23.it22a_win.team1.dashboard.App;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
